### ISSUE TITLE
Can't install gt due to sass error

### ISSUE THREAD

**Issue by jamessmythe** [rstudio/gt#254]
Installation of gt from github is failing because of a problem with the dependency sass. The following error message appears:

src/sass.hpp:52:23: fatal error: sass/base.h: No such file or directory
 #include "sass/base.h"
                       ^
compilation terminated.
make[1]: *** [src/ast.o] Error 1
make[1]: Leaving directory `/cygdrive/c/Users/JAMESS~1/AppData/Local/Temp/Rtmp6XrwRz/R.INSTALL27bc4f682ec3/sass/src-i386/libsass'
make: *** [libsass/lib/libsass.a] Error 2
ERROR: compilation failed for package 'sass'
* removing 'C:/Users/James Smythe/Documents/R/win-library/3.5/sass'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/JAMESS~1/AppData/Local/Temp/RtmpOobymS/file189073c52846/sass_0.1.0.9000.tar.gz’ had non-zero exit status

```r
devtools::install_github("rstudio/gt")

#then chose option 4 (also tried option 6)
```

**Comment by rich-iannone** [comment]
Thanks for this report! We will take a look at fixing sass right away.

**Comment by Andrzej-Andrzej** [comment]
I still can't install gt package due to sass error.

**Comment by margarethannum** [comment]
I was having the same error message. After trying everything else I could think of, I uninstalled Rtools and installed the latest version (3.5) and then was able to install `sass`/`gt` fine!

**Comment by rich-iannone** [comment]
Really sorry about these installation problems. But yes! @margarethannum is right in that Rtools 3.5 will make the installation of `sass` work (we hope to solve this issue soon and have it work with Rtools 3.4).

**Comment by Andrzej-Andrzej** [comment]
Thank you  @margarethannum, it works.

**Comment by jamessmythe** [comment]
Thanks everyone.

**Comment by jacodevries** [comment]
Any suggestions to resolve this problem when trying to install sass as a prerequisite to installing GT? 

I am using R 3.6.0 (GUI 1.70 El Capitan build (7657)). 

I have tried installing xcode as suggested in other posts, without any success in bypassing the problem.

**Comment by jacodevries** [comment]
I managed to resolve the problem with the installation on MacOS.

My working directory pointed to a Dropbox folder, which includes a space in the path.  This has not been a problem in the past using R and RStudio.  Removing the space in the path, did not solve the problem.  

The problem was solved by changing the working directory to a non-Dropbox folder.

**Comment by higgi13425** [comment]
Problem with gt and sass. Having a hard time interpreting the error message.


R> remotes::install_github("rstudio/gt")
Downloading GitHub repo rstudio/gt@master
Downloading GitHub repo rstudio/sass@master
✔  checking for file ‘/private/var/folders/_p/8ghzfv1n0qd0bp2thqt6v3qm0000gn/T/RtmpLh0VNC/remotes343972ef62a5/rstudio-sass-57c6e58/DESCRIPTION’ (661ms)
─  preparing ‘sass’: (432ms)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘sass/scripts’
─  building ‘sass_0.1.1.tar.gz’
   
* installing *source* package 'sass' ...
** using staged installation
** libs
/Library/Frameworks/R.framework/Resources/share/make/shlib.mk:14: warning: overriding commands for target `shlib-clean'
Makevars:12: warning: ignoring old commands for target `shlib-clean'
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./libsass/include  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c compile.c -o compile.o
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
In file included from compile.c:1:
/Library/Frameworks/R.framework/Resources/include/R.h:55:11: fatal error: 'stdlib.h' file not found
# include <stdlib.h> /* Not used by R itself, but widely assumed in packages */
          ^~~~~~~~~~
1 error generated.
make: *** [compile.o] Error 1
ERROR: compilation failed for package 'sass'
* removing '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sass'
Error in i.p(...) : 
  (converted from warning) installation of package '/var/folders/_p/8ghzfv1n0qd0bp2thqt6v3qm0000gn/T//RtmpLh0VNC/file343942357996/sass_0.1.1.tar.gz' had non-zero exit status
R> remotes::install_github("rstudio/sass")
Downloading GitHub repo rstudio/sass@master
✔  checking for file ‘/private/var/folders/_p/8ghzfv1n0qd0bp2thqt6v3qm0000gn/T/RtmpLh0VNC/remotes34391bf677e5/rstudio-sass-57c6e58/DESCRIPTION’ ...
─  preparing ‘sass’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘sass/scripts’
─  building ‘sass_0.1.1.tar.gz’
   
* installing *source* package 'sass' ...
** using staged installation
** libs
/Library/Frameworks/R.framework/Resources/share/make/shlib.mk:14: warning: overriding commands for target `shlib-clean'
Makevars:12: warning: ignoring old commands for target `shlib-clean'
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./libsass/include  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c compile.c -o compile.o
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
In file included from compile.c:1:
/Library/Frameworks/R.framework/Resources/include/R.h:55:11: fatal error: 'stdlib.h' file not found
# include <stdlib.h> /* Not used by R itself, but widely assumed in packages */
          ^~~~~~~~~~
1 error generated.
make: *** [compile.o] Error 1
ERROR: compilation failed for package 'sass'
* removing '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sass'
Error in i.p(...) : 
  (converted from warning) installation of package '/var/folders/_p/8ghzfv1n0qd0bp2thqt6v3qm0000gn/T//RtmpLh0VNC/file3439523969ba/sass_0.1.1.tar.gz' had non-zero exit status
R> remotes::install_github("rstudio/sass")
Downloading GitHub repo rstudio/sass@master
✔  checking for file ‘/private/var/folders/_p/8ghzfv1n0qd0bp2thqt6v3qm0000gn/T/RtmpLh0VNC/remotes34391eee7190/rstudio-sass-57c6e58/DESCRIPTION’ ...
─  preparing ‘sass’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘sass/scripts’
─  building ‘sass_0.1.1.tar.gz’
   
* installing *source* package 'sass' ...
** using staged installation
** libs
/Library/Frameworks/R.framework/Resources/share/make/shlib.mk:14: warning: overriding commands for target `shlib-clean'
Makevars:12: warning: ignoring old commands for target `shlib-clean'
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./libsass/include  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c compile.c -o compile.o
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
In file included from compile.c:1:
/Library/Frameworks/R.framework/Resources/include/R.h:55:11: fatal error: 'stdlib.h' file not found
# include <stdlib.h> /* Not used by R itself, but widely assumed in packages */
          ^~~~~~~~~~
1 error generated.
make: *** [compile.o] Error 1
ERROR: compilation failed for package 'sass'
* removing '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sass'
Error in i.p(...) : 
  (converted from warning) installation of package '/var/folders/_p/8ghzfv1n0qd0bp2thqt6v3qm0000gn/T//RtmpLh0VNC/file34393861b4cd/sass_0.1.1.tar.gz' had non-zero exit status

**Comment by rich-iannone** [comment]
The **sass** package is now on CRAN so, @higgi13425 , could you try using `install.packages("sass")` and then retry the installation of **gt**?

What needs to be done on my side is to remove `"rstudio/sass"` from `Remotes` in the DESCRIPTION file.

**Comment by higgi13425** [comment]
That does work!Though it does ask me if I want to update sass to the most recent version available. It only works if I say no (cancel by hitting return).On a Mac.now can library sass and gt
    On Thursday, June 20, 2019, 6:54:33 PM EDT, Richard Iannone <notifications@github.com> wrote:  
 
 
The sass package is now on CRAN so, @higgi13425 , could you try using install.packages("sass") and then retry the installation of gt?

What needs to be done on my side is to remove "rstudio/sass" from Remotes in the DESCRIPTION file.

**Comment by Fikrewold** [comment]
I couldn't still gt in R version 3.5.2 even though I install sass from CRAN and tried  to reinstall it.
Here is what I'm getting.


**>  remotes::install_github("rstudio/gt")
Downloading GitHub repo rstudio/gt@master
These packages have more recent versions available.
Which would you like to update?

1: All                                    
2: CRAN packages only                     
3: None                                   
4: sass (0.1.2.1 -> 4f3d4069e...) [GitHub]

Enter one or more numbers, or an empty line to skip updates:
4
sass   (0.1.2.1 -> 4f3d4069e...) [GitHub]
digest (NA      -> 0.6.20      ) [CRAN]
Installing 1 packages: digest
Installing package into ‘C:/Users/atq765/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/digest_0.6.20.zip'
Content type 'application/zip' length 222457 bytes (217 KB)
downloaded 217 KB

package ‘digest’ successfully unpacked and MD5 sums checked
Error: Failed to install 'gt' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> remotes::install_github("rstudio/gt")
Downloading GitHub repo rstudio/gt@master
These packages have more recent versions available.
Which would you like to update?

1: All                                    
2: CRAN packages only                     
3: None                                   
4: sass (0.1.2.1 -> 4f3d4069e...) [GitHub]

Enter one or more numbers, or an empty line to skip updates:
4
sass   (0.1.2.1 -> 4f3d4069e...) [GitHub]
digest (NA      -> 0.6.20      ) [CRAN]
Installing 1 packages: digest
Installing package into ‘C:/Users/atq765/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/digest_0.6.20.zip'
Content type 'application/zip' length 222457 bytes (217 KB)
downloaded 217 KB

package ‘digest’ successfully unpacked and MD5 sums checked
Error: Failed to install 'gt' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> remotes::install_github("rstudio/sass")
Downloading GitHub repo rstudio/sass@master
Installing 1 packages: digest
Installing package into ‘C:/Users/atq765/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/digest_0.6.20.zip'
Content type 'application/zip' length 222457 bytes (217 KB)
downloaded 217 KB

package ‘digest’ successfully unpacked and MD5 sums checked
Error: Failed to install 'sass' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> install.packages("sass")
Error in install.packages : Updating loaded packages**
